---
# tasks file for configureNetwork

- name: "configure network interface in networkd"
  ansible.builtin.template:
    src: interfaceNetworkD.j2
    dest: "/etc/systemd/network/{{ ansible_default_ipv4.interface }}.network"
    owner: root
    group: root
    mode: '0644'
  notify: restart networkd services
  when: ansible_distribution == 'Ubuntu'

- name: "configure network interface in ifupdown"
  ansible.builtin.template:
    src: interfaceIfupdown.j2
    dest: "/etc/network/interfaces.d/{{ ansible_default_ipv4.interface }}.network"
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'Debian'

- name: "is ipv6 disabled ?"
  ansible.builtin.copy:
    src: 70-ipv6
    dest: /etc/sysctl.d/70-ipv6.conf
    owner: root
    group: root
    mode: '0644'
  notify: apply sysctl new configuration

- name: configure resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'

- name: "is netplan absent ?"
  ansible.builtin.apt:
    name: netplan.io
    state: absent
    purge: yes
    autoremove: yes
  when: ansible_distribution == 'Ubuntu'

