---
# tasks file for configureSSH

- name: "disable login as root"
  ansible.builtin.template:
    src: sshd_rootlogin.j2
    dest: "/etc/ssh/sshd_config.d/sshd_rootlogin.conf"
  notify: restart sshd

- name: "set banner path"
  ansible.builtin.template:
    src: sshd_banner.j2
    dest: "/etc/ssh/sshd_config.d/sshd_banner.conf"
  notify: restart sshd

- name: "is banner file on host ?"
  ansible.builtin.template:
    src: issue.j2
    dest: "/etc/issue"
  notify: restart sshd 
